[package]
name = "rust_test_sensors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
docopt = "1.1.1"
i2cdev = "0.6.0"